### ISSUE TITLE
Remove unnecessary bottom scrollbar

### ISSUE THREAD

**Issue by juliesaia** [draber/draber.github.io#111]
Here with an extremely helpful red arrow:
![image](https://user-images.githubusercontent.com/76669473/159221537-162790a2-59b5-491d-874d-5d855a99f812.png)

This is because the menu is shown 10000 px off screen to the right instead of being hidden with `display: none;`

(it was annoying me and I figured it would be a 2 second fix, so that's why I made the original PR [here](https://github.com/draber/draber.github.io/pull/110) to close it)

**Comment by draber** [comment]
Can you please visit https://www.whatismybrowser.com/ and post the URL that is displayed right at the top: 
![image](https://user-images.githubusercontent.com/610502/159222010-49e6933f-db45-4229-8174-7fa9a7e204bd.png). This would help me to replicate the issue because I see this for the first time.

I can see why either your fix or setting the parent element to `overflow-x: hidden` would help, but I'd like to see the issue first-hand to be able to test the fix.

**Comment by juliesaia** [comment]
That's really strange, I'm on up to date Chrome on Windows 10 64-bit, nothing unusual (99.0.4844.74 to be exact)

I don't know how any browser would hide an element off screen automatically without some sort of `hidden` or `none`, surely if the element is being rendered there has to be a scrollbar for it

**Comment by draber** [comment]
I agree, it is really strange that I don't get a scrollbar and I will implement some hidden/none thing to fix it. There is another issue in the same area, the menu should only open on left click but does so on any click. I guess I have some work to do then...

If you are interested to contribute to SBA once in a while, please let me know. It'll be nice to have a 2nd maintainer.

**Comment by draber** [comment]
Hey Julie, 

I published a [new SBA version](https://chrome.google.com/webstore/detail/spelling-bee-assistant/ncejlmlagglodbdmkfmgnadfnbhnjcpg) that addresses the overflow bug amongst other things. Could you please confirm that the problem is now resolved?

Thanks
Dieter
